on:
  pull_request:
    types: [opened, edited, reopened]
    branches: [main]
jobs:
  check-pr-title:
    runs-on: ubuntu-20.04
    steps:
    - name : Check PR Title
      if: ${{ github.event.pull_request.title == '' }}
      run: |
        echo "ERROR: The Title of your PR must not be empty !"
        exit 1
