name: Check PR Description
on:
  pull_request:
    types: [opened, edited, reopened]
    branches: [main]
jobs:
  Check-PR-Description:
    runs-on: ubuntu-latest
    env:
      pr_template_message: "PR Description template:\nSummary of the PR changes\nJIRA link\n[optional]Checklist"
    steps:
    - name : Check if PR Description is Empty
      if: ${{ github.event.pull_request.body == '' }}
      run: |
        echo "ERROR: The Description of your PR must not be empty !"
        exit 1
    - name : PR Description Not Empty check success
      run: |
        echo "SUCCESS: PR Description empty validation!"
    - name: Check if PR description matches the required format
      id: check_description
      run: |
        # Extract PR description
        description="${{ github.event.pull_request.body }}"

        # Remove leading/trailing whitespace and collapse multiple blank lines
        formatted_description=$(echo "$description" | sed '/^[[:space:]]*$/d')

        # Check if we have at least one non-empty line
        lines_count=$(echo "$formatted_description" | wc -l)
        if [ "$lines_count" -lt 1 ]; then
          echo "$pr_template_message"
          exit 1
        fi
        echo "SUCCESS: PR Description non-empty line validation!"

        # Check if any line contains a URL starting with "https://"
        url_found=false
        while IFS= read -r line; do
          if echo "$line" | grep -q '^https://'; then
            url_found=true
            break
          fi
        done <<< "$formatted_description"
        
        if [ "$url_found" = false ]; then
          echo "$pr_template_message"
          exit 1
        fi
        echo "SUCCESS: PR Description URL validation!"

    - name: Set status check result
      if: failure()
      run: exit 1
