name: Send Slack Alert
on:
  pull_request:
    types: [opened, edited, reopened]
    branches: [main]
jobs:
  Send-Slack-Approval-Request:
    runs-on: ubuntu-latest
    steps:
    - name : Send Slack Approval Request
      id: slack
      uses: slackapi/slack-github-action@v1.27.0
      with:
        payload: |
          {
            "author": "Test_Author",
            "repository": "Test_Repo",
            "title": "Test_Title",
            "description": "Test_Description",
            "url": "https://www.github.com"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
