name: Send Slack Alert
on:
  pull_request:
    types: [opened, edited, reopened]
    branches: [main]
jobs:
  Send-Slack-Approval-Request:
    runs-on: ubuntu-latest
    env:
      pr_title: "${{ github.event.pull_request.title }}"
    steps:
    - name : Send Slack Approval Request
      id: slack
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: chat.postMessage
        payload: |
          {
            "author": "${{ github.actor }}",
            "repository": "${{ github.repositoryUrl }}",
            "title": "${{ github.event.pull_request.title }}",
            "url": "${{ github.event.pull_request.html_url }}"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
